analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance & correctness
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - discarded_futures
    - use_build_context_synchronously
    # Code quality
    - unawaited_futures
    - prefer_single_quotes

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
